module:
  _target_: models.pl_modules.CrossPLModule
  RAdam:
    _target_: torch.optim.RAdam
    lr: 2e-5
  Adafactor:
    _target_: transformers.Adafactor
    lr: 3e-5
    weight_decay: 0.01
    scale_parameter: False
    relative_step: False
  lr_scheduler:     
    num_warmup_steps: 10
    num_training_steps: 10000
  opt: "Adafactor" #RAdam
  model:
    _target_: models.model_cross.xCoRe_system
    language_model: "deberta-v3-large"
    huggingface_model_name: "microsoft/deberta-v3-large"
    freeze_encoder: False
    span_representation: "concat_start_end"
    cluster_representation: "transformer" #dot, transformer, s2e
    t: "mes" #mes,  s2e